# Generated by Django 6.0.3 on 2026-06-29 07:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCommitmentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('button_text', models.CharField(blank=True, max_length=100, null=True)),
                ('button_url', models.CharField(blank=True, help_text='Example: /sustainability/ or https://example.com/report', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Commitment Section',
                'verbose_name_plural': 'About Commitment Sections',
            },
        ),
        migrations.CreateModel(
            name='AboutCoreValueSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Core Value Heading',
                'verbose_name_plural': 'About Core Value Headings',
            },
        ),
        migrations.CreateModel(
            name='AboutFounderSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/founder/')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Founder Section',
                'verbose_name_plural': 'About Founder Sections',
            },
        ),
        migrations.CreateModel(
            name='AboutHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Hero',
                'verbose_name_plural': 'About Heroes',
            },
        ),
        migrations.CreateModel(
            name='AboutStorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_title', models.CharField(blank=True, max_length=150, null=True)),
                ('story_text', models.TextField(blank=True, null=True)),
                ('mission_title', models.CharField(blank=True, max_length=150, null=True)),
                ('mission_text', models.TextField(blank=True, null=True)),
                ('side_image', models.ImageField(blank=True, null=True, upload_to='about/story/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Story Section',
                'verbose_name_plural': 'About Story Sections',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('button_text', models.CharField(default='Shop Now', max_length=100)),
                ('button_link', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Category', help_text='This heading appears inside the Shop dropdown.', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('hex_code', models.CharField(blank=True, help_text='Example: #ff3366', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactFAQSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Frequently Asked Questions', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact FAQ Heading',
                'verbose_name_plural': 'Contact FAQ Heading',
            },
        ),
        migrations.CreateModel(
            name='ContactHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='contact/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact Hero',
                'verbose_name_plural': 'Contact Hero',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ContactServiceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Customer Services', max_length=150)),
                ('email_title', models.CharField(default='Email Us', max_length=100)),
                ('service_email', models.EmailField(default='padmavathyprasanna4@gmail.com', help_text='Contact form messages will be sent to this email.', max_length=254)),
                ('call_title', models.CharField(default='Call Us', max_length=100)),
                ('phone_number_1', models.CharField(default='+91-1234567890', max_length=30)),
                ('phone_number_2', models.CharField(blank=True, default='+91-1234567890', max_length=30, null=True)),
                ('track_order_text', models.CharField(default='Track You Order', max_length=100)),
                ('track_order_url', models.CharField(blank=True, default='#', max_length=255, null=True)),
                ('cancel_order_text', models.CharField(default='Cancel Order', max_length=100)),
                ('cancel_order_url', models.CharField(blank=True, default='#', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact Service Info',
                'verbose_name_plural': 'Contact Service Info',
            },
        ),
        migrations.CreateModel(
            name='DiscountOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Example: 10-20%, Buy 1 Get 1, Flat ₹100 Off', max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedProductSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Featured Products', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Featured Product Section',
                'verbose_name_plural': 'Featured Product Section',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('quick_links', 'Quick Links'), ('support', 'Support')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(help_text='Example: /shop/ or https://example.com', max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Footer Link',
                'verbose_name_plural': 'Footer Links',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FooterSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='footer/logo/')),
                ('address', models.TextField(default='3rd Floor, Valasaravakam,\nChennai - 600800')),
                ('quick_links_title', models.CharField(default='Quick Links', max_length=100)),
                ('support_title', models.CharField(default='Support', max_length=100)),
                ('social_media_title', models.CharField(default='Social Media', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Footer Setting',
                'verbose_name_plural': 'Footer Settings',
            },
        ),
        migrations.CreateModel(
            name='FooterSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(help_text='Example: https://instagram.com/yourpage')),
                ('icon_class', models.CharField(blank=True, help_text='Font Awesome class. Example: fab fa-facebook-f or fab fa-instagram', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Footer Social Media',
                'verbose_name_plural': 'Footer Social Media',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HappyCustomerSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Happy Customers', max_length=150)),
                ('autoplay_seconds', models.PositiveIntegerField(default=4, help_text='Carousel auto-change time in seconds.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Happy Customer Section',
                'verbose_name_plural': 'Happy Customer Section',
            },
        ),
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('content_text', models.TextField()),
                ('left_image', models.ImageField(upload_to='images/')),
                ('right_image', models.ImageField(upload_to='images/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Home Content',
                'verbose_name_plural': 'Home Contents',
            },
        ),
        migrations.CreateModel(
            name='NavbarLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(blank=True, help_text='Example: /, /offers/, /about/, /contact/. Use # for Shop dropdown.', max_length=255, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='navbar_icons/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OfferBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload full offer banner image', upload_to='offers/banners/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number shows first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Offer Banner',
                'verbose_name_plural': 'Offer Banners',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OfferProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload offer product image', upload_to='offers/products/')),
                ('image_name', models.CharField(help_text='Product name shown below image', max_length=150)),
                ('description', models.TextField(help_text='Product description shown below image name')),
                ('original_price', models.DecimalField(decimal_places=2, help_text='Original price. This will show with strikeout.', max_digits=10)),
                ('discounted_price', models.DecimalField(decimal_places=2, help_text='Discounted price. This price will be added to cart.', max_digits=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number shows first. Add 3 active products for offer page.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Offer Product',
                'verbose_name_plural': 'Offer Products',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OfferSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Buy 1 Get 1 Free', help_text='Example: Buy 1 Get 1 Free', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Offer Section Heading',
                'verbose_name_plural': 'Offer Section Heading',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(blank=True, help_text='Example: credit-card, net-banking, upi', unique=True)),
                ('icon_image', models.ImageField(blank=True, help_text='Upload payment icon image like Credit Card, Net Banking, UPI.', null=True, upload_to='payment_icons/')),
                ('icon_text', models.CharField(blank=True, help_text='Optional fallback text/icon. Example: 💳', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Powered by Performance Ingredients', max_length=200)),
                ('autoplay_seconds', models.PositiveIntegerField(default=15, help_text='Time taken for one full auto-scroll loop')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Example: ₹0 - ₹499', max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('min_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, help_text="Leave empty for 'and above'. Example: ₹1,100 & Above", max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['min_price', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subtitle', models.CharField(default='3-5 Business Day', max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='site_logo/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Setting', max_length=100)),
                ('estimated_shipping', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10)),
                ('gst', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscribeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_image', models.ImageField(blank=True, help_text='Left side image for category page subscribe banner only.', null=True, upload_to='subscribe_banner/')),
                ('heading', models.CharField(default='Join our Beauty Circle', max_length=150)),
                ('description', models.TextField(default='Be the first to know about new arrivals, exclusive discounts, and special flash sales.')),
                ('email_placeholder', models.CharField(default='Enter You Email', max_length=100)),
                ('button_text', models.CharField(default='Register', max_length=50)),
                ('background_color', models.CharField(default='linear-gradient(135deg, #f58fba, #f72585)', help_text='Example: #F72585 or linear-gradient(135deg, #f58fba, #f72585)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Subscribe Banner',
                'verbose_name_plural': 'Subscribe Banner',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='TopCategorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Top Categories', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Top Category Section',
                'verbose_name_plural': 'Top Category Section',
            },
        ),
        migrations.CreateModel(
            name='WhyGlowifySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Why Glowify', max_length=150)),
                ('main_image', models.ImageField(help_text='Left side girl/product image', upload_to='why_glowify/')),
                ('flower_color', models.CharField(default='#F72585', help_text='Flower background color. Example: #F72585', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Why Glowify Section',
                'verbose_name_plural': 'Why Glowify Section',
            },
        ),
        migrations.CreateModel(
            name='AboutCoreValueCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='about/core-values/icons/')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='dashboard.aboutcorevaluesection')),
            ],
            options={
                'verbose_name': 'About Core Value Card',
                'verbose_name_plural': 'About Core Value Cards',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactFAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Example: Is Cream Luxe Finish lipstick long-lasting?', max_length=255)),
                ('answer', models.TextField(help_text='Example: Yes, it lasts up to 6–8 hours with minimal touch-ups.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number shows first.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faq_items', to='dashboard.contactfaqsection')),
            ],
            options={
                'verbose_name': 'Contact FAQ Item',
                'verbose_name_plural': 'Contact FAQ Items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HappyCustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_image', models.ImageField(help_text='Customer profile image', upload_to='happy_customers/')),
                ('customer_name', models.CharField(help_text='Example: Ananya R.', max_length=120)),
                ('location', models.CharField(blank=True, help_text='Example: Bangalore', max_length=120)),
                ('rating', models.PositiveIntegerField(default=5, help_text='Enter rating from 1 to 5')),
                ('review_text', models.TextField(help_text='Customer feedback text')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='dashboard.happycustomersection')),
            ],
            options={
                'verbose_name': 'Happy Customer Review',
                'verbose_name_plural': 'Happy Customer Reviews',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery')], default='processing', max_length=30)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('phonepe_merchant_order_id', models.CharField(blank=True, help_text='Unique merchant order ID sent to PhonePe.', max_length=63, null=True, unique=True)),
                ('phonepe_transaction_id', models.CharField(blank=True, default='', max_length=120)),
                ('phonepe_response', models.TextField(blank=True, default='', help_text='Raw PhonePe status/callback response saved for debugging.')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('offer_discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total discount applied from claimed offers.', max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('gst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='dashboard.paymentmethod')),
                ('shipping_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='dashboard.shippingmethod')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='performance_ingredients/')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='dashboard.performancesection')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('name', models.CharField(max_length=150)),
                ('shade_name', models.CharField(blank=True, help_text='Example: Rose Blush, Ruby Desire', max_length=120)),
                ('description', models.TextField(blank=True, default='', help_text='Full product description shown on the product detail page.')),
                ('tagline', models.CharField(blank=True, default='', help_text='Short bold sentence shown below the rating. Example: Luxury. Comfort. Timeless Color.', max_length=200)),
                ('how_to_use', models.TextField(blank=True, default='', help_text='Steps or guidance for the How to Use tab on the product detail page.')),
                ('benefits', models.TextField(blank=True, default='', help_text='One benefit per line. These lines appear in the Benefits tab.')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=1, default=Decimal('4.8'), max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=214)),
                ('badge', models.CharField(blank=True, choices=[('best_seller', 'Best Seller'), ('new', 'New'), ('trending', 'Trending'), ('hair_pick', 'Hair Pick'), ('skin_loving', 'Skin Loving')], help_text='Optional badge for home featured products.', max_length=30, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number shows first.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Turn on to show this product on home page Featured Products section.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='dashboard.brand')),
                ('colors', models.ManyToManyField(blank=True, help_text='Select product colors for Color filter.', related_name='products', to='dashboard.color')),
                ('discount_options', models.ManyToManyField(blank=True, related_name='products', to='dashboard.discountoption')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['order', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('shade_name', models.CharField(blank=True, max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Original price before offer discount.', max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount amount for this item.', max_digits=10)),
                ('is_offer_item', models.BooleanField(default=False, help_text='True if this order item came from claimed offer.')),
                ('voucher_code', models.CharField(blank=True, default='', help_text='Voucher code used for this offer item.', max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.product')),
            ],
        ),
        migrations.CreateModel(
            name='ExclusiveOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_image', models.ImageField(blank=True, help_text='Upload image for exclusive offer section and cart page.', null=True, upload_to='exclusive_offers/')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('voucher_code', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusive_offers', to='dashboard.product')),
            ],
            options={
                'verbose_name': 'Exclusive Claim Offer',
                'verbose_name_plural': 'Exclusive Claim Offers',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(help_text='Example: Eye Make Up, Skin Care, Lipsticks', max_length=100)),
                ('heading', models.CharField(blank=True, help_text='Page heading. Example: Eye Makeup', max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='Example: eyemakeup, skincare, lipsticks', max_length=150, null=True, unique=True)),
                ('page_url', models.CharField(blank=True, help_text='Auto generated if empty. Example: /eyemakeup/', max_length=255)),
                ('search_placeholder', models.CharField(default='Search products...', help_text='Navbar search placeholder for this page.', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='dashboard.category')),
            ],
            options={
                'verbose_name': 'Page Item',
                'verbose_name_plural': 'Page Items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='page_item',
            field=models.ForeignKey(blank=True, help_text='Select Page Item like Eye Make Up, Skin Care, Lipsticks.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='dashboard.subcategory'),
        ),
        migrations.CreateModel(
            name='HomeFlashSaleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Flash Sale', max_length=100)),
                ('sale_text', models.CharField(default='50 % Off', max_length=100)),
                ('quote_text', models.CharField(default='Glow Confidently every Day', max_length=200)),
                ('button_text', models.CharField(default='Shop Now', max_length=50)),
                ('left_image', models.ImageField(blank=True, null=True, upload_to='home_flash_sale/')),
                ('right_image', models.ImageField(blank=True, null=True, upload_to='home_flash_sale/')),
                ('background_color', models.CharField(default='#f72585', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flash_sale_sections', to='dashboard.subcategory')),
            ],
            options={
                'verbose_name': 'Home Flash Sale Section',
                'verbose_name_plural': 'Home Flash Sale Sections',
            },
        ),
        migrations.CreateModel(
            name='TopCategoryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='top_categories/')),
                ('title', models.CharField(help_text='Example: Lipsticks, Skincare, Eye Makeup', max_length=100)),
                ('subtitle', models.CharField(blank=True, help_text='Example: Vibrant & Bold Color', max_length=150)),
                ('button_text', models.CharField(default='Shop Now', max_length=50)),
                ('custom_link', models.CharField(blank=True, help_text='Optional. Example: /shop/eyemakeup/. If empty, selected category page link is used.', max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category_page', models.ForeignKey(blank=True, help_text='Select category page. Shop Now will navigate to this category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_category_cards', to='dashboard.subcategory')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='dashboard.topcategorysection')),
            ],
            options={
                'verbose_name': 'Top Category Card',
                'verbose_name_plural': 'Top Category Cards',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ManyToManyField(blank=True, related_name='cart_user_profiles', to='dashboard.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wishlist', models.ManyToManyField(blank=True, related_name='wishlisted_by_profiles', to='dashboard.product')),
            ],
        ),
        migrations.CreateModel(
            name='WhyGlowifyPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Example: 01, 02, 03, 04', max_length=10)),
                ('title', models.CharField(help_text='Example: Clean Beauty Promise', max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='dashboard.whyglowifysection')),
            ],
            options={
                'verbose_name': 'Why Glowify Point',
                'verbose_name_plural': 'Why Glowify Points',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='Used for guest users before login.', max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_offer_claimed', models.BooleanField(default=False, help_text='True when user clicked Claim This Offer.')),
                ('voucher_code', models.CharField(blank=True, default='', help_text='Voucher code applied for this offer product.', max_length=50)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, help_text='Offer price saved at claim time.', max_digits=10, null=True)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original price saved at claim time.', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
                ('claimed_offer', models.ForeignKey(blank=True, help_text='If this cart item came from Claim This Offer, store that offer here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='dashboard.exclusiveoffer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='dashboard.product')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'product'), name='unique_cart_product_per_user'), models.UniqueConstraint(condition=models.Q(('session_key__isnull', False), ('user__isnull', True)), fields=('session_key', 'product'), name='unique_cart_product_per_guest')],
            },
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='Used for guest users before login.', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='dashboard.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wishlist Item',
                'verbose_name_plural': 'Wishlist Items',
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'product'), name='unique_wishlist_product_per_user'), models.UniqueConstraint(condition=models.Q(('session_key__isnull', False), ('user__isnull', True)), fields=('session_key', 'product'), name='unique_wishlist_product_per_guest')],
            },
        ),
    ]
