# Generated by Django 6.0.3 on 2026-05-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Upload payment icon image like Credit Card, Net Banking, UPI.', null=True, upload_to='payment_icons/'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='icon_text',
            field=models.CharField(blank=True, help_text='Optional fallback text/icon. Example: 💳', max_length=20),
        ),
    ]
