# Generated by Django 6.0.3 on 2026-05-07 08:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_footerlink_footersetting_footersocialmedia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerlink',
            options={'ordering': ['display_order', 'id'], 'verbose_name': 'Footer Link', 'verbose_name_plural': 'Footer Links'},
        ),
        migrations.AlterModelOptions(
            name='footersetting',
            options={'verbose_name': 'Footer Setting', 'verbose_name_plural': 'Footer Settings'},
        ),
        migrations.AlterModelOptions(
            name='footersocialmedia',
            options={'ordering': ['display_order', 'id'], 'verbose_name': 'Footer Social Media', 'verbose_name_plural': 'Footer Social Media'},
        ),
        migrations.AddField(
            model_name='footersetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footersetting',
            name='quick_links_title',
            field=models.CharField(default='Quick Links', max_length=100),
        ),
        migrations.AddField(
            model_name='footersetting',
            name='social_media_title',
            field=models.CharField(default='Social Media', max_length=100),
        ),
        migrations.AddField(
            model_name='footersetting',
            name='support_title',
            field=models.CharField(default='Support', max_length=100),
        ),
        migrations.AlterField(
            model_name='footersetting',
            name='address',
            field=models.TextField(default='3rd Floor, Valasaravakam,\nChennai - 600800'),
        ),
        migrations.AlterField(
            model_name='footersetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='footer/logo/'),
        ),
        migrations.AlterField(
            model_name='footersocialmedia',
            name='icon_class',
            field=models.CharField(blank=True, help_text='Font Awesome class. Example: fab fa-facebook-f or fab fa-instagram', max_length=100),
        ),
        migrations.AlterField(
            model_name='footersocialmedia',
            name='url',
            field=models.URLField(help_text='Example: https://instagram.com/yourpage'),
        ),
    ]
