# Generated by Django 6.0.3 on 2026-05-08 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_footerlink_options_alter_footersetting_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exclusiveoffer',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Exclusive Claim Offer', 'verbose_name_plural': 'Exclusive Claim Offers'},
        ),
        migrations.RemoveField(
            model_name='exclusiveoffer',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='exclusiveoffer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='exclusiveoffer',
            name='image',
        ),
        migrations.RemoveField(
            model_name='exclusiveoffer',
            name='save_text',
        ),
        migrations.RemoveField(
            model_name='exclusiveoffer',
            name='title',
        ),
        migrations.AddField(
            model_name='exclusiveoffer',
            name='offer_image',
            field=models.ImageField(blank=True, help_text='Upload image for exclusive offer section and cart page.', null=True, upload_to='exclusive_offers/'),
        ),
        migrations.AlterField(
            model_name='exclusiveoffer',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='exclusiveoffer',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exclusiveoffer',
            name='original_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='exclusiveoffer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusive_offers', to='dashboard.product'),
        ),
        migrations.AlterField(
            model_name='exclusiveoffer',
            name='voucher_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
