# Generated by Django 6.0.3 on 2026-06-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_exclusiveoffer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='phonepe_merchant_order_id',
            field=models.CharField(blank=True, help_text='Unique merchant order ID sent to PhonePe.', max_length=63, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phonepe_response',
            field=models.TextField(blank=True, default='', help_text='Raw PhonePe status/callback response saved for debugging.'),
        ),
        migrations.AddField(
            model_name='order',
            name='phonepe_transaction_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='benefits',
            field=models.TextField(blank=True, default='', help_text='One benefit per line. These lines appear in the Benefits tab.'),
        ),
        migrations.AddField(
            model_name='product',
            name='how_to_use',
            field=models.TextField(blank=True, default='', help_text='Steps or guidance for the How to Use tab on the product detail page.'),
        ),
        migrations.AddField(
            model_name='product',
            name='tagline',
            field=models.CharField(blank=True, default='', help_text='Short bold sentence shown below the rating. Example: Luxury. Comfort. Timeless Color.', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Full product description shown on the product detail page.'),
        ),
    ]
